/* Generated by tools/build-web-demo.js. Do not edit directly. */
(function () {
'use strict';
// ---- src/core/types.ts ----
var EntityType = /*#__PURE__*/ function(EntityType) {
    EntityType["GENERAL"] = "general";
    EntityType["SOLDIER"] = "soldier";
    EntityType["ROOK"] = "rook";
    EntityType["KNIGHT"] = "knight";
    EntityType["CANNON"] = "cannon";
    EntityType["ELEPHANT"] = "elephant";
    EntityType["ADVISOR"] = "advisor";
    EntityType["KING"] = "general";
    EntityType["PAWN"] = "soldier";
    return EntityType;
}({});
var Team = /*#__PURE__*/ function(Team) {
    Team["PLAYER"] = "player";
    Team["ENEMY"] = "enemy";
    Team["ITEM"] = "item";
    return Team;
}({});
var GamePhase = /*#__PURE__*/ function(GamePhase) {
    GamePhase["PLAYER_TURN"] = "player_turn";
    GamePhase["ENEMY_TURN"] = "enemy_turn";
    GamePhase["ANIMATING"] = "animating";
    GamePhase["SPAWNING"] = "spawning";
    GamePhase["SHOP"] = "shop";
    GamePhase["GAME_OVER"] = "game_over";
    return GamePhase;
}({});
const SKILL_IDS = [
    'armor',
    'intimidate',
    'castling',
    'aura',
    'siege'
];
var SkillType = /*#__PURE__*/ function(SkillType) {
    SkillType["DAMAGE"] = "damage";
    SkillType["MOVEMENT"] = "movement";
    SkillType["DEFENSE"] = "defense";
    SkillType["UTILITY"] = "utility";
    return SkillType;
}({});
var Faction = /*#__PURE__*/ function(Faction) {
    Faction["GENERAL"] = "general";
    Faction["ROOK"] = "rook";
    Faction["KNIGHT"] = "knight";
    Faction["CANNON"] = "cannon";
    Faction["ELEPHANT"] = "elephant";
    Faction["SOLDIER"] = "soldier";
    return Faction;
}({});

// ---- src/core/GameConfig.ts ----
const BOARD_WIDTH = 9;
const BOARD_HEIGHT = 10;
const GRID_SIZE = BOARD_WIDTH;
const COLORS = {
    board: {
        background: '#f4dfb8',
        grid: '#8b5a2b',
        riverText: '#9b6a37',
        palace: '#b47a3c',
        cell: '#f8e8c8',
        cellHover: '#ead1a5'
    },
    highlight: {
        accessible: 'rgba(70, 150, 95, 0.24)',
        accessibleDot: '#3f9b62',
        threatened: 'rgba(198, 54, 48, 0.28)',
        aura: 'rgba(120, 95, 190, 0.22)'
    },
    entity: {
        player: {
            fill: '#f7d79b',
            stroke: '#b7332f',
            shadow: 'rgba(183, 51, 47, 0.35)',
            text: '#a32220'
        },
        soldier: {
            fill: '#f3d2a4',
            stroke: '#6f3d25',
            shadow: 'rgba(111, 61, 37, 0.28)',
            text: '#34251d'
        },
        pawn: {
            fill: '#f3d2a4',
            stroke: '#6f3d25',
            shadow: 'rgba(111, 61, 37, 0.28)',
            text: '#34251d'
        },
        rook: {
            fill: '#e7b16f',
            stroke: '#8f3c2d',
            shadow: 'rgba(143, 60, 45, 0.32)',
            text: '#3f2418'
        },
        knight: {
            fill: '#edc77d',
            stroke: '#9a6429',
            shadow: 'rgba(154, 100, 41, 0.3)',
            text: '#352315'
        },
        cannon: {
            fill: '#e98663',
            stroke: '#a9362d',
            shadow: 'rgba(169, 54, 45, 0.36)',
            text: '#2f1b17'
        },
        elephant: {
            fill: '#d7bd83',
            stroke: '#7f6840',
            shadow: 'rgba(127, 104, 64, 0.28)',
            text: '#2d2518'
        },
        advisor: {
            fill: '#d9c49c',
            stroke: '#74614a',
            shadow: 'rgba(116, 97, 74, 0.28)',
            text: '#2d241c'
        },
        general: {
            fill: '#c8463f',
            stroke: '#7d211f',
            shadow: 'rgba(125, 33, 31, 0.38)',
            text: '#fff3dd'
        }
    },
    text: {
        primary: '#3f2b1f',
        secondary: '#7a5f45',
        accent: '#b7332f',
        playerSymbol: '#a32220',
        enemySymbol: '#34251d'
    },
    background: '#f8efe0',
    button: {
        normal: '#b98a55',
        hover: '#a67645',
        active: '#8f6037',
        text: '#ffffff'
    }
};
const ENTITY_SYMBOLS = {
    PLAYER: '帅',
    GENERAL: '将',
    SOLDIER: '兵',
    PAWN: '兵',
    ROOK: '车',
    KNIGHT: '马',
    CANNON: '炮',
    ELEPHANT: '象',
    ADVISOR: '士'
};
const ENTITY_NAMES = {
    PLAYER: '帅',
    GENERAL: '将',
    SOLDIER: '兵',
    PAWN: '兵',
    ROOK: '车',
    KNIGHT: '马',
    CANNON: '炮',
    ELEPHANT: '象',
    ADVISOR: '士'
};
const SPAWN_CONFIG = {
    soldierChance: 0.55,
    pawnChance: 0.55,
    knightStartTurn: 5,
    knightMaxCount: 3,
    knightBaseChance: 0.2,
    knightChanceGrowth: 0.05,
    knightMaxChance: 0.5,
    cannonStartTurn: 8,
    cannonMaxCount: 2,
    cannonBaseChance: 0.18,
    cannonChanceGrowth: 0.035,
    cannonMaxChance: 0.42,
    elephantStartTurn: 10,
    elephantMaxCount: 2,
    elephantBaseChance: 0.14,
    elephantChanceGrowth: 0.03,
    elephantMaxChance: 0.35,
    rookStartTurn: 12,
    rookMaxCount: 2,
    rookBaseChance: 0.15,
    rookChanceGrowth: 0.04,
    rookMaxChance: 0.4,
    advisorStartTurn: 14,
    advisorMaxCount: 2,
    advisorBaseChance: 0.12,
    advisorChanceGrowth: 0.025,
    advisorMaxChance: 0.3,
    generalStartTurn: 18,
    generalMaxCount: 1,
    generalBaseChance: 0.1,
    generalChanceGrowth: 0.02,
    generalMaxChance: 0.24,
    maxEnemyBase: 6,
    maxEnemyGrowth: 5,
    maxEnemyCap: 14
};
const SCORE_CONFIG = {
    soldierKill: 1,
    pawnKill: 1,
    knightKill: 3,
    cannonKill: 4,
    elephantKill: 4,
    advisorKill: 4,
    rookKill: 5,
    generalKill: 8,
    maxKillStreak: 3,
    deadCleanupInterval: 10
};
const SHOP_PRICE = 5;
const SHOP_OFFER_COUNT = 3;

// ---- src/core/utils.ts ----
function posEq(a, b) {
    return a.x === b.x && a.y === b.y;
}
function posKey(pos) {
    return `${pos.x},${pos.y}`;
}
function posFromKey(key) {
    const [x, y] = key.split(',').map(Number);
    return {
        x,
        y
    };
}
function posClone(pos) {
    return {
        x: pos.x,
        y: pos.y
    };
}
function isValidPos(pos, width, height = width) {
    return pos.x >= 0 && pos.x < width && pos.y >= 0 && pos.y < height;
}
function manhattanDistance(a, b) {
    return Math.abs(a.x - b.x) + Math.abs(a.y - b.y);
}
function euclideanDistanceSquared(a, b) {
    const dx = a.x - b.x;
    const dy = a.y - b.y;
    return dx * dx + dy * dy;
}
function sign(n) {
    return n === 0 ? 0 : n < 0 ? -1 : 1;
}
let idCounter = 0;
function generateId() {
    return `entity_${++idCounter}`;
}
function resetIdCounter() {
    idCounter = 0;
}
function randomPos(width, height = width) {
    return {
        x: Math.floor(Math.random() * width),
        y: Math.floor(Math.random() * height)
    };
}
function shuffle(array) {
    const result = [
        ...array
    ];
    for(let i = result.length - 1; i > 0; i--){
        const j = Math.floor(Math.random() * (i + 1));
        [result[i], result[j]] = [
            result[j],
            result[i]
        ];
    }
    return result;
}
function getAllPositions(width, height = width) {
    const positions = [];
    for(let y = 0; y < height; y++){
        for(let x = 0; x < width; x++){
            positions.push({
                x,
                y
            });
        }
    }
    return positions;
}

// ---- src/core/SkillSpecs.ts ----
const SKILL_SPECS = {
    armor: {
        id: 'armor',
        name: '铁甲护身',
        desc: '抵挡一次致命攻击',
        flavor: '为自身披上一层护甲。当受到会造成死亡的攻击时，护甲自动消耗一层将其抵挡，免于一死。',
        types: [
            SkillType.DEFENSE
        ],
        faction: Faction.GENERAL,
        icon: '\u{1F6E1}',
        maxLevel: 5,
        scaling: {
            armorLayers: [
                1,
                1,
                2,
                2,
                3
            ]
        }
    },
    intimidate: {
        id: 'intimidate',
        name: '借刀杀人',
        desc: '相邻敌人有概率被冻结',
        flavor: '玩家的气势令相邻的敌人心生胆怯。每轮敌人行动前，紧靠你的敌人有一定概率被吓住，该回合无法移动。',
        types: [
            SkillType.UTILITY
        ],
        faction: Faction.GENERAL,
        icon: '\u{1F628}',
        maxLevel: 5,
        scaling: {
            freezeChance: [
                0.30,
                0.45,
                0.60,
                0.75,
                0.75
            ]
        }
    },
    castling: {
        id: 'castling',
        name: '王车易位',
        desc: '可传送到任意空格',
        flavor: '传承自象棋的特殊走法。冷却就绪时，本回合可以无视距离限制，直接传送到棋盘上任意一个空格。传送后进入冷却。',
        types: [
            SkillType.MOVEMENT
        ],
        faction: Faction.GENERAL,
        icon: '⚡',
        maxLevel: 5,
        scaling: {
            cooldown: [
                4,
                3,
                2,
                2,
                2
            ]
        }
    },
    aura: {
        id: 'aura',
        name: '将军威势',
        desc: '敌人回避你的周围',
        flavor: '散发出令敌人不敢靠近的王者气场。敌人计算移动路线时，会主动避开你周围的格子。',
        types: [
            SkillType.UTILITY
        ],
        faction: Faction.GENERAL,
        icon: '\u{1F451}',
        maxLevel: 3,
        scaling: {
            auraRange: [
                1,
                1,
                2
            ]
        }
    },
    siege: {
        id: 'siege',
        name: '兵临城下',
        desc: '定期自动消灭一个小兵',
        flavor: '来自四面八方的力量汇聚，定期自动击杀场上一名随机小兵。无小兵时该次效果跳过。',
        types: [
            SkillType.DAMAGE
        ],
        faction: Faction.GENERAL,
        icon: '⚔',
        maxLevel: 5,
        scaling: {
            interval: [
                3,
                2,
                1,
                1,
                1
            ]
        }
    }
};
function getScalingValue(spec, valueName, level) {
    const values = spec.scaling[valueName];
    if (!values || values.length === 0) return 0;
    const idx = Math.max(0, Math.min(level - 1, values.length - 1));
    return values[idx];
}
function getSkillsByFaction(faction) {
    return Object.values(SKILL_SPECS).filter((s)=>s.faction === faction);
}

// ---- src/core/SkillSystem.ts ----
const SKILL_DEFS = {
    armor: {
        name: '铁甲护身',
        icon: '\u{1F6E1}',
        desc: '抵挡一次致命攻击',
        fullDesc: '为自身披上一层护甲。当受到会造成死亡的攻击时，护甲自动消耗一层将其抵挡，免于一死。',
        descStack: (lv)=>`当前护甲层数：${lv} 层（可继续叠加）`
    },
    intimidate: {
        name: '借刀杀人',
        icon: '\u{1F628}',
        desc: '相邻敌人有概率被冻结',
        fullDesc: '玩家的气势令相邻的敌人心生胆怯。每轮敌人行动前，紧靠你的敌人有一定概率被吓住，该回合无法移动。',
        descStack: (lv)=>`当前冻结概率：${Math.round(getScalingValue(SKILL_SPECS.intimidate, 'freezeChance', lv) * 100)}%（最高75%）`
    },
    castling: {
        name: '王车易位',
        icon: '⚡',
        desc: '可传送到任意空格',
        fullDesc: '传承自象棋的特殊走法。冷却就绪时，本回合可以无视距离限制，直接传送到棋盘上任意一个空格。传送后进入冷却。',
        descStack: (lv)=>`冷却：${getScalingValue(SKILL_SPECS.castling, 'cooldown', lv)} 回合（叠加可缩短）`
    },
    aura: {
        name: '将军威势',
        icon: '\u{1F451}',
        desc: '敌人回避你的周围',
        fullDesc: '散发出令敌人不敢靠近的王者气场。敌人计算移动路线时，会主动避开你周围的格子，不会主动走入威慑范围内。',
        descStack: (lv)=>`威慑范围：${getScalingValue(SKILL_SPECS.aura, 'auraRange', lv)} 格（最大2格）`
    },
    siege: {
        name: '兵临城下',
        icon: '⚔',
        desc: '定期自动消灭一个小兵',
        fullDesc: '来自四面八方的力量汇聚，定期自动击杀场上一名随机小兵。无小兵时该次效果跳过。',
        descStack: (lv)=>`触发间隔：每 ${getScalingValue(SKILL_SPECS.siege, 'interval', lv)} 回合（叠加可加快）`
    }
};
function getCastlingCooldown(level) {
    return getScalingValue(SKILL_SPECS.castling, 'cooldown', level);
}
function getIntimidateChance(level) {
    return getScalingValue(SKILL_SPECS.intimidate, 'freezeChance', level);
}
function getSiegeInterval(level) {
    return getScalingValue(SKILL_SPECS.siege, 'interval', level);
}
function getAuraRange(level) {
    return getScalingValue(SKILL_SPECS.aura, 'auraRange', level);
}
function grantSkill(state, skillId) {
    const spec = SKILL_SPECS[skillId];
    if (!spec || state.skills[skillId] >= spec.maxLevel) return false;
    state.skills[skillId]++;
    if (skillId === 'castling' && state.skills.castling === 1) {
        state.castlingCooldown = 0;
    }
    if (skillId === 'siege' && state.skills.siege === 1) {
        state.siegeTimer = getScalingValue(SKILL_SPECS.siege, 'interval', 1);
    }
    return true;
}
function applyIntimidateFreeze(state) {
    state.frozenEnemies.clear();
    if (state.skills.intimidate <= 0 || !state.player) return;
    const chance = getScalingValue(SKILL_SPECS.intimidate, 'freezeChance', state.skills.intimidate);
    const px = state.player.position.x;
    const py = state.player.position.y;
    for (const enemy of state.enemies){
        if (enemy.isDead) continue;
        const chebyshev = Math.max(Math.abs(enemy.position.x - px), Math.abs(enemy.position.y - py));
        if (chebyshev <= 1 && Math.random() < chance) {
            state.frozenEnemies.add(enemy.id);
        }
    }
}
function applySiegeEffect(state) {
    if (state.skills.siege <= 0) return null;
    state.siegeTimer--;
    if (state.siegeTimer <= 0) {
        state.siegeTimer = getScalingValue(SKILL_SPECS.siege, 'interval', state.skills.siege);
        const livingPawns = state.enemies.filter((e)=>!e.isDead && e.type === EntityType.SOLDIER);
        if (livingPawns.length > 0) {
            const target = livingPawns[Math.floor(Math.random() * livingPawns.length)];
            target.isDead = true;
            const cell = state.grid.cells.get(posKey(target.position));
            if (cell) cell.entity = null;
            return target.id;
        }
    }
    return null;
}
function applyArmor(state) {
    if (state.skills.armor <= 0) return false;
    state.skills.armor--;
    return true;
}
function checkCastlingUsed(state, movedDist) {
    if (state.skills.castling <= 0 || state.castlingCooldown > 0) return false;
    if (movedDist > 1) {
        state.castlingCooldown = getScalingValue(SKILL_SPECS.castling, 'cooldown', state.skills.castling);
        return true;
    }
    return false;
}
function tickCastlingCooldown(state) {
    if (state.skills.castling > 0 && state.castlingCooldown > 0) {
        state.castlingCooldown--;
    }
}

// ---- src/core/ShopSystem.ts ----
function getNextShopThreshold(lastScore) {
    if (lastScore === 0) return 3;
    if (lastScore === 3) return 7;
    return lastScore + 5;
}
function awardScore(state, amount) {
    const gained = Math.max(0, Math.floor(amount));
    state.score += gained;
    state.coins += gained;
    return gained;
}
function getAvailableShopSkills(state) {
    return SKILL_IDS.filter((id)=>state.skills[id] < SKILL_SPECS[id].maxLevel);
}
function generateShopOffers(state) {
    const available = getAvailableShopSkills(state);
    if (available.length === 0) return [];
    const count = Math.min(SHOP_OFFER_COUNT, available.length);
    const offers = [];
    for(let i = 0; i < count; i++){
        const skillId = available[Math.floor(Math.random() * available.length)];
        offers.push({
            id: `shop_${state.lastShopScore}_${i}`,
            skillId,
            price: SHOP_PRICE,
            purchased: false
        });
    }
    return offers;
}
function maybeOpenShop(state, now = Date.now()) {
    let latestThreshold = state.lastShopScore;
    let nextThreshold = getNextShopThreshold(latestThreshold);
    while(state.score >= nextThreshold){
        latestThreshold = nextThreshold;
        nextThreshold = getNextShopThreshold(latestThreshold);
    }
    if (latestThreshold === state.lastShopScore) return false;
    state.lastShopScore = latestThreshold;
    state.shopOffers = generateShopOffers(state);
    if (state.shopOffers.length === 0) return false;
    state.phase = GamePhase.SHOP;
    state.shopOpenedAt = now;
    state.animating = false;
    return true;
}
function canPurchaseOffer(state, offer) {
    if (state.phase !== GamePhase.SHOP) return 'not_in_shop';
    if (offer.purchased) return 'sold_out';
    if (state.skills[offer.skillId] >= SKILL_SPECS[offer.skillId].maxLevel) return 'max_level';
    if (state.coins < offer.price) return 'insufficient_coins';
    return 'purchased';
}
function purchaseShopOffer(state, offerId) {
    const offer = state.shopOffers.find((item)=>item.id === offerId);
    if (!offer) return 'invalid_offer';
    const status = canPurchaseOffer(state, offer);
    if (status !== 'purchased') return status;
    if (!grantSkill(state, offer.skillId)) return 'max_level';
    state.coins -= offer.price;
    offer.purchased = true;
    return 'purchased';
}
function closeShop(state, now = Date.now()) {
    if (state.phase !== GamePhase.SHOP) return state.phase;
    if (state.shopOpenedAt !== undefined) {
        state.pausedDurationMs += Math.max(0, now - state.shopOpenedAt);
    }
    state.phase = GamePhase.PLAYER_TURN;
    state.shopOpenedAt = undefined;
    state.shopOffers = [];
    return state.phase;
}
function getElapsedGameMs(state, now = Date.now()) {
    const end = state.finishedAt ?? now;
    const activeShopPause = state.phase === GamePhase.SHOP && state.shopOpenedAt !== undefined ? Math.max(0, end - state.shopOpenedAt) : 0;
    return Math.max(0, end - state.startedAt - state.pausedDurationMs - activeShopPause);
}

// ---- src/core/Leaderboard.ts ----
const MAX_ENTRIES = 10;
const MAX_NAME_LENGTH = 12;
const ANONYMOUS_NAME = '匿名';
function compareEntries(a, b) {
    if (a.score !== b.score) return b.score - a.score;
    if (a.elapsedSec !== b.elapsedSec) return a.elapsedSec - b.elapsedSec;
    return a.timestamp - b.timestamp;
}
function normalizeName(raw) {
    const trimmed = (raw || '').trim();
    if (trimmed.length === 0) return ANONYMOUS_NAME;
    if (trimmed.length > MAX_NAME_LENGTH) return trimmed.slice(0, MAX_NAME_LENGTH);
    return trimmed;
}
function parseEntries(raw) {
    if (!raw) return [];
    try {
        const data = JSON.parse(raw);
        if (!Array.isArray(data)) return [];
        const entries = [];
        for (const item of data){
            if (item && typeof item.name === 'string' && typeof item.score === 'number' && typeof item.turn === 'number' && typeof item.elapsedSec === 'number' && typeof item.isVictory === 'boolean' && typeof item.timestamp === 'number') {
                entries.push(item);
            }
        }
        entries.sort(compareEntries);
        return entries.slice(0, MAX_ENTRIES);
    } catch (_e) {
        return [];
    }
}
function loadLeaderboard(storage) {
    return parseEntries(storage.read());
}
function insertEntry(storage, entry) {
    const next = parseEntries(storage.read());
    next.push(entry);
    next.sort(compareEntries);
    const truncated = next.slice(0, MAX_ENTRIES);
    try {
        storage.write(JSON.stringify(truncated));
    } catch (_e) {}
    return truncated;
}
function clearLeaderboard(storage) {
    try {
        storage.write(JSON.stringify([]));
    } catch (_e) {}
}
function getRank(entries, entry) {
    for(let i = 0; i < entries.length; i++){
        if (entries[i].timestamp === entry.timestamp && entries[i].name === entry.name) {
            return i + 1;
        }
    }
    return null;
}
function formatElapsed(totalSec) {
    const sec = Math.max(0, Math.floor(totalSec));
    const h = Math.floor(sec / 3600);
    const m = Math.floor(sec % 3600 / 60);
    const s = sec % 60;
    const pad = (n)=>n < 10 ? '0' + n : '' + n;
    if (h > 0) return `${pad(h)}:${pad(m)}:${pad(s)}`;
    return `${pad(m)}:${pad(s)}`;
}

// ---- src/core/GameLogic.ts ----
const ORTHOGONAL = [
    {
        dx: 0,
        dy: -1
    },
    {
        dx: 0,
        dy: 1
    },
    {
        dx: -1,
        dy: 0
    },
    {
        dx: 1,
        dy: 0
    }
];
const DIAGONAL = [
    {
        dx: -1,
        dy: -1
    },
    {
        dx: 1,
        dy: -1
    },
    {
        dx: -1,
        dy: 1
    },
    {
        dx: 1,
        dy: 1
    }
];
function createEntity(type, team, position) {
    return {
        id: generateId(),
        type,
        team,
        position: posClone(position),
        isDead: false
    };
}
function createGrid(width = BOARD_WIDTH, height = BOARD_HEIGHT) {
    const grid = {
        width,
        height,
        size: width,
        cells: new Map()
    };
    for(let y = 0; y < height; y++){
        for(let x = 0; x < width; x++){
            const cell = {
                position: {
                    x,
                    y
                },
                entity: null,
                isPlayerAccessible: false,
                isThreatened: false
            };
            grid.cells.set(posKey({
                x,
                y
            }), cell);
        }
    }
    return grid;
}
function createInitialState() {
    const grid = createGrid();
    const playerPos = randomPos(BOARD_WIDTH, BOARD_HEIGHT);
    const player = createEntity(EntityType.GENERAL, Team.PLAYER, playerPos);
    const playerCell = grid.cells.get(posKey(playerPos));
    if (playerCell) {
        playerCell.entity = player;
    }
    const skills = {
        armor: 0,
        intimidate: 0,
        castling: 0,
        aura: 0,
        siege: 0
    };
    const state = {
        phase: GamePhase.PLAYER_TURN,
        turn: 1,
        score: 0,
        coins: 0,
        grid,
        entities: new Map([
            [
                player.id,
                player
            ]
        ]),
        player,
        enemies: [],
        animating: false,
        lastShopScore: 0,
        shopOffers: [],
        pausedDurationMs: 0,
        skills,
        castlingCooldown: 0,
        siegeTimer: 0,
        frozenEnemies: new Set(),
        killStreak: 0,
        startedAt: Date.now()
    };
    updatePlayerAccessiblePositions(state);
    updateThreatMap(state);
    return state;
}
function getEmptyCells(state) {
    const empty = [];
    for (const [, cell] of state.grid.cells){
        if (cell.entity === null) empty.push(posClone(cell.position));
    }
    return empty;
}
function valid(pos, grid) {
    return isValidPos(pos, grid.width, grid.height);
}
function cellAt(grid, pos) {
    return grid.cells.get(posKey(pos));
}
function isEnemyPalace(pos) {
    return pos.x >= 3 && pos.x <= 5 && pos.y >= 0 && pos.y <= 2;
}
function isEnemySide(pos) {
    return pos.y <= 4;
}
function updatePlayerAccessiblePositions(state) {
    for (const cell of state.grid.cells.values())cell.isPlayerAccessible = false;
    if (!state.player) return;
    const { x, y } = state.player.position;
    const directions = [
        {
            dx: -1,
            dy: -1
        },
        {
            dx: 0,
            dy: -1
        },
        {
            dx: 1,
            dy: -1
        },
        {
            dx: -1,
            dy: 0
        },
        {
            dx: 0,
            dy: 0
        },
        {
            dx: 1,
            dy: 0
        },
        {
            dx: -1,
            dy: 1
        },
        {
            dx: 0,
            dy: 1
        },
        {
            dx: 1,
            dy: 1
        }
    ];
    for (const dir of directions){
        const newPos = {
            x: x + dir.dx,
            y: y + dir.dy
        };
        if (valid(newPos, state.grid)) {
            const cell = cellAt(state.grid, newPos);
            if (cell) cell.isPlayerAccessible = true;
        }
    }
    if (state.skills.castling > 0 && state.castlingCooldown <= 0) {
        for (const cell of state.grid.cells.values()){
            if (!cell.entity || cell.entity === state.player) cell.isPlayerAccessible = true;
        }
    }
}
function getPlayerAccessiblePositions(state) {
    const positions = [];
    for (const cell of state.grid.cells.values()){
        if (cell.isPlayerAccessible) positions.push(posClone(cell.position));
    }
    return positions;
}
function getThreatRange(entity, grid) {
    switch(entity.type){
        case EntityType.SOLDIER:
            return getSoldierMoves(entity, grid);
        case EntityType.ROOK:
            return getRookThreat(entity, grid);
        case EntityType.KNIGHT:
            return getKnightMoves(entity, grid);
        case EntityType.CANNON:
            return getCannonThreat(entity, grid);
        case EntityType.ELEPHANT:
            return getElephantMoves(entity, grid);
        case EntityType.ADVISOR:
            return getAdvisorMoves(entity, grid);
        case EntityType.GENERAL:
            return getGeneralThreat(entity, grid);
        default:
            return [];
    }
}
function getSoldierMoves(entity, grid) {
    const moves = [
        {
            x: entity.position.x,
            y: entity.position.y + 1
        }
    ];
    if (entity.position.y >= 5) {
        moves.push({
            x: entity.position.x - 1,
            y: entity.position.y
        }, {
            x: entity.position.x + 1,
            y: entity.position.y
        });
    }
    return moves.filter((pos)=>valid(pos, grid));
}
function getRookThreat(entity, grid) {
    const threats = [];
    for (const dir of ORTHOGONAL){
        let pos = posClone(entity.position);
        while(true){
            pos = {
                x: pos.x + dir.dx,
                y: pos.y + dir.dy
            };
            if (!valid(pos, grid)) break;
            threats.push(posClone(pos));
            if (cellAt(grid, pos)?.entity) break;
        }
    }
    return threats;
}
function getRookMoves(entity, grid) {
    return getSlidingMoves(entity, grid, ORTHOGONAL);
}
function getCannonMoves(entity, grid) {
    return getSlidingMoves(entity, grid, ORTHOGONAL);
}
function getSlidingMoves(entity, grid, directions) {
    const moves = [];
    for (const dir of directions){
        let pos = posClone(entity.position);
        while(true){
            pos = {
                x: pos.x + dir.dx,
                y: pos.y + dir.dy
            };
            if (!valid(pos, grid)) break;
            if (cellAt(grid, pos)?.entity) break;
            moves.push(posClone(pos));
        }
    }
    return moves;
}
function getCannonThreat(entity, grid) {
    const threats = [];
    for (const dir of ORTHOGONAL){
        let pos = posClone(entity.position);
        let hasScreen = false;
        while(true){
            pos = {
                x: pos.x + dir.dx,
                y: pos.y + dir.dy
            };
            if (!valid(pos, grid)) break;
            const occupied = Boolean(cellAt(grid, pos)?.entity);
            if (!hasScreen) {
                if (occupied) hasScreen = true;
                continue;
            }
            threats.push(posClone(pos));
            if (occupied) break;
        }
    }
    return threats;
}
function getKnightMoves(entity, grid) {
    const moves = [
        {
            dx: 1,
            dy: -2,
            leg: {
                dx: 0,
                dy: -1
            }
        },
        {
            dx: 2,
            dy: -1,
            leg: {
                dx: 1,
                dy: 0
            }
        },
        {
            dx: 2,
            dy: 1,
            leg: {
                dx: 1,
                dy: 0
            }
        },
        {
            dx: 1,
            dy: 2,
            leg: {
                dx: 0,
                dy: 1
            }
        },
        {
            dx: -1,
            dy: 2,
            leg: {
                dx: 0,
                dy: 1
            }
        },
        {
            dx: -2,
            dy: 1,
            leg: {
                dx: -1,
                dy: 0
            }
        },
        {
            dx: -2,
            dy: -1,
            leg: {
                dx: -1,
                dy: 0
            }
        },
        {
            dx: -1,
            dy: -2,
            leg: {
                dx: 0,
                dy: -1
            }
        }
    ];
    return moves.filter((move)=>!cellAt(grid, {
            x: entity.position.x + move.leg.dx,
            y: entity.position.y + move.leg.dy
        })?.entity).map((move)=>({
            x: entity.position.x + move.dx,
            y: entity.position.y + move.dy
        })).filter((pos)=>valid(pos, grid));
}
function getElephantMoves(entity, grid) {
    return DIAGONAL.map((dir)=>({
            target: {
                x: entity.position.x + dir.dx * 2,
                y: entity.position.y + dir.dy * 2
            },
            eye: {
                x: entity.position.x + dir.dx,
                y: entity.position.y + dir.dy
            }
        })).filter((move)=>valid(move.target, grid) && isEnemySide(move.target) && !cellAt(grid, move.eye)?.entity).map((move)=>move.target);
}
function getAdvisorMoves(entity, grid) {
    return DIAGONAL.map((dir)=>({
            x: entity.position.x + dir.dx,
            y: entity.position.y + dir.dy
        })).filter((pos)=>valid(pos, grid) && isEnemyPalace(pos));
}
function getGeneralMoves(entity, grid) {
    return ORTHOGONAL.map((dir)=>({
            x: entity.position.x + dir.dx,
            y: entity.position.y + dir.dy
        })).filter((pos)=>valid(pos, grid) && isEnemyPalace(pos));
}
function getGeneralThreat(entity, grid) {
    const threats = getGeneralMoves(entity, grid);
    for (const dy of [
        -1,
        1
    ]){
        let pos = {
            x: entity.position.x,
            y: entity.position.y
        };
        while(true){
            pos = {
                x: pos.x,
                y: pos.y + dy
            };
            if (!valid(pos, grid)) break;
            threats.push(posClone(pos));
            if (cellAt(grid, pos)?.entity) break;
        }
    }
    return threats;
}
function getLegalMoves(entity, grid) {
    switch(entity.type){
        case EntityType.SOLDIER:
            return getSoldierMoves(entity, grid);
        case EntityType.ROOK:
            return getRookMoves(entity, grid);
        case EntityType.KNIGHT:
            return getKnightMoves(entity, grid);
        case EntityType.CANNON:
            return getCannonMoves(entity, grid);
        case EntityType.ELEPHANT:
            return getElephantMoves(entity, grid);
        case EntityType.ADVISOR:
            return getAdvisorMoves(entity, grid);
        case EntityType.GENERAL:
            return getGeneralMoves(entity, grid);
        default:
            return [];
    }
}
function updateThreatMap(state) {
    for (const cell of state.grid.cells.values())cell.isThreatened = false;
    for (const enemy of state.enemies){
        if (enemy.isDead) continue;
        const threats = getThreatRange(enemy, state.grid);
        for (const threat of threats){
            const cell = cellAt(state.grid, threat);
            if (cell) cell.isThreatened = true;
        }
        enemy.threatRange = threats;
    }
}
function calculateEnemyMoves(state) {
    if (!state.player) return;
    for (const enemy of state.enemies){
        if (enemy.isDead) continue;
        const candidates = getLegalMoves(enemy, state.grid).filter((pos)=>{
            const cell = cellAt(state.grid, pos);
            return cell && (!cell.entity || cell.entity === state.player);
        });
        let bestMove = null;
        let bestDist = Infinity;
        for (const candidate of candidates){
            const dist = Math.abs(candidate.x - state.player.position.x) + Math.abs(candidate.y - state.player.position.y);
            if (dist < bestDist) {
                bestDist = dist;
                bestMove = candidate;
            }
        }
        enemy.nextMove = bestMove || undefined;
    }
}
function enemyCount(state, type) {
    return state.enemies.filter((e)=>!e.isDead && e.type === type).length;
}
function spawnOne(state, type, candidates) {
    const shuffled = shuffle(candidates.filter((pos)=>!cellAt(state.grid, pos)?.entity));
    if (shuffled.length === 0) return false;
    const pos = shuffled[0];
    const enemy = createEntity(type, Team.ENEMY, pos);
    state.entities.set(enemy.id, enemy);
    state.enemies.push(enemy);
    const cell = cellAt(state.grid, pos);
    if (cell) cell.entity = enemy;
    return true;
}
function allEmpty(state) {
    return getEmptyCells(state);
}
function enemySideEmpty(state) {
    return getEmptyCells(state).filter(isEnemySide);
}
function palaceEmpty(state) {
    return getEmptyCells(state).filter(isEnemyPalace);
}
function spawnEnemies(state) {
    const turn = state.turn;
    const cfg = SPAWN_CONFIG;
    const livingEnemies = state.enemies.filter((e)=>!e.isDead);
    const maxEnemies = Math.min(cfg.maxEnemyBase + Math.floor(turn / cfg.maxEnemyGrowth), cfg.maxEnemyCap);
    if (livingEnemies.length >= maxEnemies) return;
    if (Math.random() < cfg.soldierChance) {
        spawnOne(state, EntityType.SOLDIER, enemySideEmpty(state));
    }
    if (turn >= cfg.knightStartTurn && enemyCount(state, EntityType.KNIGHT) < cfg.knightMaxCount) {
        const chance = Math.min(cfg.knightBaseChance + (turn - cfg.knightStartTurn) * cfg.knightChanceGrowth, cfg.knightMaxChance);
        if (Math.random() < chance) spawnOne(state, EntityType.KNIGHT, allEmpty(state));
    }
    if (turn >= cfg.cannonStartTurn && enemyCount(state, EntityType.CANNON) < cfg.cannonMaxCount) {
        const chance = Math.min(cfg.cannonBaseChance + (turn - cfg.cannonStartTurn) * cfg.cannonChanceGrowth, cfg.cannonMaxChance);
        if (Math.random() < chance) spawnOne(state, EntityType.CANNON, allEmpty(state));
    }
    if (turn >= cfg.elephantStartTurn && enemyCount(state, EntityType.ELEPHANT) < cfg.elephantMaxCount) {
        const chance = Math.min(cfg.elephantBaseChance + (turn - cfg.elephantStartTurn) * cfg.elephantChanceGrowth, cfg.elephantMaxChance);
        if (Math.random() < chance) spawnOne(state, EntityType.ELEPHANT, enemySideEmpty(state));
    }
    if (turn >= cfg.rookStartTurn && enemyCount(state, EntityType.ROOK) < cfg.rookMaxCount) {
        const chance = Math.min(cfg.rookBaseChance + (turn - cfg.rookStartTurn) * cfg.rookChanceGrowth, cfg.rookMaxChance);
        if (Math.random() < chance) spawnOne(state, EntityType.ROOK, allEmpty(state));
    }
    if (turn >= cfg.advisorStartTurn && enemyCount(state, EntityType.ADVISOR) < cfg.advisorMaxCount) {
        const chance = Math.min(cfg.advisorBaseChance + (turn - cfg.advisorStartTurn) * cfg.advisorChanceGrowth, cfg.advisorMaxChance);
        if (Math.random() < chance) spawnOne(state, EntityType.ADVISOR, palaceEmpty(state));
    }
    if (turn >= cfg.generalStartTurn && enemyCount(state, EntityType.GENERAL) < cfg.generalMaxCount) {
        const chance = Math.min(cfg.generalBaseChance + (turn - cfg.generalStartTurn) * cfg.generalChanceGrowth, cfg.generalMaxChance);
        if (Math.random() < chance) spawnOne(state, EntityType.GENERAL, palaceEmpty(state));
    }
}
function scoreFor(type) {
    switch(type){
        case EntityType.SOLDIER:
            return SCORE_CONFIG.soldierKill;
        case EntityType.KNIGHT:
            return SCORE_CONFIG.knightKill;
        case EntityType.CANNON:
            return SCORE_CONFIG.cannonKill;
        case EntityType.ELEPHANT:
            return SCORE_CONFIG.elephantKill;
        case EntityType.ADVISOR:
            return SCORE_CONFIG.advisorKill;
        case EntityType.ROOK:
            return SCORE_CONFIG.rookKill;
        case EntityType.GENERAL:
            return SCORE_CONFIG.generalKill;
        default:
            return 0;
    }
}
function handlePlayerMove(state, targetPos) {
    const result = {
        moved: false,
        scoreGained: 0,
        castlingUsed: false,
        shopOpened: false
    };
    if (state.phase !== GamePhase.PLAYER_TURN || !state.player) return result;
    const targetCell = cellAt(state.grid, targetPos);
    if (!targetCell || !targetCell.isPlayerAccessible) return result;
    let killedEnemy = false;
    if (targetCell.entity && targetCell.entity.team === Team.ENEMY) {
        const enemy = targetCell.entity;
        enemy.isDead = true;
        killedEnemy = true;
        state.killStreak = Math.min(state.killStreak + 1, SCORE_CONFIG.maxKillStreak);
        const gained = scoreFor(enemy.type) * state.killStreak;
        result.scoreGained = awardScore(state, gained);
        result.killedEnemyId = enemy.id;
        result.killedEnemyType = enemy.type;
    }
    if (!killedEnemy) state.killStreak = 0;
    const oldCell = cellAt(state.grid, state.player.position);
    if (oldCell) oldCell.entity = null;
    const movedDist = Math.max(Math.abs(targetPos.x - state.player.position.x), Math.abs(targetPos.y - state.player.position.y));
    result.castlingUsed = checkCastlingUsed(state, movedDist);
    state.player.position = posClone(targetPos);
    targetCell.entity = state.player;
    calculateEnemyMoves(state);
    state.phase = GamePhase.ENEMY_TURN;
    state.animating = true;
    result.shopOpened = maybeOpenShop(state);
    if (result.shopOpened) {
        updatePlayerAccessiblePositions(state);
        updateThreatMap(state);
    }
    result.moved = true;
    return result;
}
function executeEnemyTurn(state) {
    const result = {
        playerDead: false,
        armorBlocked: false,
        siegeKillId: null
    };
    if (!state.player || state.phase !== GamePhase.ENEMY_TURN) return result;
    applyIntimidateFreeze(state);
    updateThreatMap(state);
    let playerDead = false;
    let killer = null;
    for (const enemy of state.enemies){
        if (enemy.isDead) continue;
        for (const threat of enemy.threatRange || []){
            if (posEq(threat, state.player.position)) {
                playerDead = true;
                killer = enemy;
                break;
            }
        }
        if (playerDead) break;
    }
    if (playerDead && applyArmor(state)) {
        playerDead = false;
        result.armorBlocked = true;
    }
    if (playerDead) {
        state.player.isDead = true;
        state.phase = GamePhase.GAME_OVER;
        state.isVictory = false;
        state.finishedAt = Date.now();
        state.deathMessage = `被 ${killer?.type || '敌人'} 击杀`;
        result.playerDead = true;
        return result;
    }
    for (const enemy of state.enemies){
        if (enemy.isDead || state.frozenEnemies.has(enemy.id) || !enemy.nextMove) continue;
        if (state.skills.aura > 0) {
            const auraRange = getAuraRange(state.skills.aura);
            const dist = Math.max(Math.abs(enemy.nextMove.x - state.player.position.x), Math.abs(enemy.nextMove.y - state.player.position.y));
            if (dist <= auraRange) continue;
        }
        const targetCell = cellAt(state.grid, enemy.nextMove);
        if (targetCell && !targetCell.entity) {
            const oldCell = cellAt(state.grid, enemy.position);
            if (oldCell) oldCell.entity = null;
            targetCell.entity = enemy;
            enemy.position = posClone(enemy.nextMove);
        }
    }
    result.siegeKillId = applySiegeEffect(state);
    if (result.siegeKillId) awardScore(state, SCORE_CONFIG.soldierKill);
    tickCastlingCooldown(state);
    state.turn++;
    if (state.turn % SCORE_CONFIG.deadCleanupInterval === 0) {
        state.enemies = state.enemies.filter((e)=>!e.isDead);
    }
    state.phase = GamePhase.SPAWNING;
    spawnEnemies(state);
    updatePlayerAccessiblePositions(state);
    updateThreatMap(state);
    state.phase = GamePhase.PLAYER_TURN;
    state.animating = false;
    maybeOpenShop(state);
    return result;
}
function isGameOver(state) {
    return state.phase === GamePhase.GAME_OVER;
}
function formatBoardAscii(state) {
    const symbols = {
        [EntityType.GENERAL]: 'G',
        [EntityType.SOLDIER]: 'S',
        [EntityType.ROOK]: 'R',
        [EntityType.KNIGHT]: 'N',
        [EntityType.CANNON]: 'C',
        [EntityType.ELEPHANT]: 'E',
        [EntityType.ADVISOR]: 'A'
    };
    let board = '';
    for(let y = 0; y < state.grid.height; y++){
        let row = '';
        for(let x = 0; x < state.grid.width; x++){
            const cell = cellAt(state.grid, {
                x,
                y
            });
            row += cell?.entity ? symbols[cell.entity.type] || '?' : '.';
            row += ' ';
        }
        board += row.trim() + '\n';
    }
    return board;
}

// ---- src/render/canvas-renderer.ts ----
function formatGameTime(state) {
    return formatElapsed(getElapsedGameMs(state) / 1000);
}
class CanvasRenderer {
    canvas;
    ctx;
    cellSize;
    padding;
    boardWidth;
    boardHeight;
    constructor(canvas){
        this.canvas = canvas;
        const ctx = canvas.getContext('2d');
        if (!ctx) throw new Error('Unable to get Canvas 2D context');
        this.ctx = ctx;
        this.padding = 28;
        const usableWidth = canvas.width - this.padding * 2 - 180;
        const usableHeight = canvas.height - this.padding * 2;
        this.cellSize = Math.floor(Math.min(usableWidth / (BOARD_WIDTH - 1), usableHeight / (BOARD_HEIGHT - 1)));
        this.boardWidth = this.cellSize * (BOARD_WIDTH - 1);
        this.boardHeight = this.cellSize * (BOARD_HEIGHT - 1);
    }
    render(state) {
        this.clear();
        this.drawBoardBackground();
        this.drawGrid();
        this.drawHighlights(state);
        this.drawEntities(state);
        this.drawUI(state);
    }
    clear() {
        this.ctx.fillStyle = COLORS.background;
        this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
    }
    origin() {
        return {
            x: this.padding,
            y: this.padding
        };
    }
    point(pos) {
        const start = this.origin();
        return {
            x: start.x + pos.x * this.cellSize,
            y: start.y + pos.y * this.cellSize
        };
    }
    drawBoardBackground() {
        const start = this.origin();
        this.ctx.fillStyle = COLORS.board.background;
        this.ctx.fillRect(start.x - this.cellSize * 0.45, start.y - this.cellSize * 0.45, this.boardWidth + this.cellSize * 0.9, this.boardHeight + this.cellSize * 0.9);
    }
    drawGrid() {
        const start = this.origin();
        const endX = start.x + this.boardWidth;
        const endY = start.y + this.boardHeight;
        const riverTop = start.y + 4 * this.cellSize;
        const riverBottom = start.y + 5 * this.cellSize;
        this.ctx.strokeStyle = COLORS.board.grid;
        this.ctx.lineWidth = 2;
        for(let y = 0; y < BOARD_HEIGHT; y++){
            const py = start.y + y * this.cellSize;
            this.ctx.beginPath();
            this.ctx.moveTo(start.x, py);
            this.ctx.lineTo(endX, py);
            this.ctx.stroke();
        }
        for(let x = 0; x < BOARD_WIDTH; x++){
            const px = start.x + x * this.cellSize;
            this.ctx.beginPath();
            this.ctx.moveTo(px, start.y);
            this.ctx.lineTo(px, riverTop);
            this.ctx.moveTo(px, riverBottom);
            this.ctx.lineTo(px, endY);
            this.ctx.stroke();
        }
        this.drawPalace(0);
        this.drawPalace(7);
        this.drawRiverText();
    }
    drawPalace(topRow) {
        const a = this.point({
            x: 3,
            y: topRow
        });
        const b = this.point({
            x: 5,
            y: topRow
        });
        const c = this.point({
            x: 3,
            y: topRow + 2
        });
        const d = this.point({
            x: 5,
            y: topRow + 2
        });
        this.ctx.strokeStyle = COLORS.board.palace;
        this.ctx.lineWidth = 1.5;
        this.ctx.beginPath();
        this.ctx.moveTo(a.x, a.y);
        this.ctx.lineTo(d.x, d.y);
        this.ctx.moveTo(b.x, b.y);
        this.ctx.lineTo(c.x, c.y);
        this.ctx.stroke();
    }
    drawRiverText() {
        const start = this.origin();
        const y = start.y + this.cellSize * 4.5;
        this.ctx.fillStyle = COLORS.board.riverText;
        this.ctx.font = `bold ${Math.floor(this.cellSize * 0.42)}px "SimSun", "KaiTi", serif`;
        this.ctx.textAlign = 'center';
        this.ctx.textBaseline = 'middle';
        this.ctx.fillText('楚 河', start.x + this.cellSize * 2, y);
        this.ctx.fillText('汉 界', start.x + this.cellSize * 6, y);
    }
    drawHighlights(state) {
        for(let y = 0; y < state.grid.height; y++){
            for(let x = 0; x < state.grid.width; x++){
                const cell = state.grid.cells.get(`${x},${y}`);
                if (!cell) continue;
                const p = this.point({
                    x,
                    y
                });
                if (cell.isThreatened) {
                    this.ctx.fillStyle = COLORS.highlight.threatened;
                    this.ctx.beginPath();
                    this.ctx.arc(p.x, p.y, this.cellSize * 0.36, 0, Math.PI * 2);
                    this.ctx.fill();
                }
                if (cell.isPlayerAccessible && !cell.entity) {
                    this.ctx.fillStyle = COLORS.highlight.accessible;
                    this.ctx.beginPath();
                    this.ctx.arc(p.x, p.y, this.cellSize * 0.32, 0, Math.PI * 2);
                    this.ctx.fill();
                    this.ctx.fillStyle = COLORS.highlight.accessibleDot;
                    this.ctx.beginPath();
                    this.ctx.arc(p.x, p.y, Math.max(3, this.cellSize * 0.08), 0, Math.PI * 2);
                    this.ctx.fill();
                }
            }
        }
    }
    drawEntities(state) {
        for (const entity of state.entities.values()){
            if (entity.isDead) continue;
            const p = this.point(entity.position);
            this.drawPiece(p.x, p.y, this.cellSize * 0.72, entity);
        }
    }
    drawPiece(x, y, size, entity) {
        const style = this.getEntityStyle(entity);
        const radius = size / 2;
        this.ctx.fillStyle = style.shadow;
        this.ctx.beginPath();
        this.ctx.arc(x + 3, y + 4, radius, 0, Math.PI * 2);
        this.ctx.fill();
        this.ctx.fillStyle = style.fill;
        this.ctx.beginPath();
        this.ctx.arc(x, y, radius, 0, Math.PI * 2);
        this.ctx.fill();
        this.ctx.strokeStyle = style.stroke;
        this.ctx.lineWidth = 3;
        this.ctx.beginPath();
        this.ctx.arc(x, y, radius, 0, Math.PI * 2);
        this.ctx.stroke();
        this.ctx.lineWidth = 1.5;
        this.ctx.beginPath();
        this.ctx.arc(x, y, radius * 0.78, 0, Math.PI * 2);
        this.ctx.stroke();
        this.ctx.fillStyle = style.text || COLORS.text.enemySymbol;
        this.ctx.font = `bold ${Math.floor(size * 0.46)}px "KaiTi", "SimSun", serif`;
        this.ctx.textAlign = 'center';
        this.ctx.textBaseline = 'middle';
        this.ctx.fillText(this.getEntitySymbol(entity), x, y + 1);
    }
    getEntityStyle(entity) {
        if (entity.team === 'player') return COLORS.entity.player;
        return COLORS.entity[entity.type] || COLORS.entity.soldier;
    }
    getEntitySymbol(entity) {
        if (entity.team === 'player') return ENTITY_SYMBOLS.PLAYER;
        const key = entity.type.toUpperCase();
        return ENTITY_SYMBOLS[key] || '?';
    }
    drawUI(state) {
        const leftX = this.padding + this.boardWidth + 56;
        const topY = this.padding;
        this.ctx.fillStyle = COLORS.text.primary;
        this.ctx.font = 'bold 24px Arial, sans-serif';
        this.ctx.textAlign = 'left';
        this.ctx.textBaseline = 'top';
        this.ctx.fillText('肉鸽象棋', leftX, topY);
        this.ctx.fillStyle = COLORS.text.secondary;
        this.ctx.font = '16px Arial, sans-serif';
        this.ctx.fillText(`回合: ${state.turn}`, leftX, topY + 42);
        this.ctx.fillText(`分数: ${state.score}`, leftX, topY + 68);
        this.ctx.fillText(`金币: ${state.coins}`, leftX, topY + 94);
        this.ctx.fillText(`时间: ${formatGameTime(state)}`, leftX, topY + 120);
        this.ctx.fillText(`阶段: ${this.getPhaseText(state.phase)}`, leftX, topY + 146);
        const skillsBaseY = topY + 186;
        const skillsHeight = this.drawSkillsPanel(state, leftX, skillsBaseY);
        if (state.phase === 'game_over') {
            const gameOverY = skillsBaseY + skillsHeight + 16;
            this.ctx.fillStyle = COLORS.text.accent;
            this.ctx.font = 'bold 20px Arial, sans-serif';
            this.ctx.fillText('游戏结束', leftX, gameOverY);
            this.ctx.font = '14px Arial, sans-serif';
            this.ctx.fillText(state.deathMessage || '被将死', leftX, gameOverY + 30);
            this.ctx.fillText('刷新页面重新开始', leftX, gameOverY + 56);
        }
    }
    drawSkillsPanel(state, x, y) {
        const titleHeight = 22;
        const lineHeight = 22;
        this.ctx.fillStyle = COLORS.text.primary;
        this.ctx.font = 'bold 16px Arial, sans-serif';
        this.ctx.fillText('技能', x, y);
        let cursorY = y + titleHeight;
        let hasAny = false;
        for (const id of Object.keys(state.skills)){
            const level = state.skills[id];
            if (!level || level <= 0) continue;
            const def = SKILL_DEFS[id];
            if (!def) continue;
            hasAny = true;
            this.ctx.fillStyle = COLORS.text.secondary;
            this.ctx.font = '14px Arial, sans-serif';
            this.ctx.fillText(`${def.icon} ${def.name} Lv.${level}`, x, cursorY);
            cursorY += lineHeight;
        }
        if (!hasAny) {
            this.ctx.fillStyle = COLORS.text.secondary;
            this.ctx.font = '13px Arial, sans-serif';
            this.ctx.fillText('达到积分阈值可在商店购买技能', x, cursorY);
            cursorY += lineHeight;
        }
        return cursorY - y;
    }
    getPhaseText(phase) {
        const phaseMap = {
            player_turn: '你的回合',
            enemy_turn: '敌人行动',
            animating: '动画中',
            spawning: '生成中',
            shop: '商店',
            game_over: '游戏结束'
        };
        return phaseMap[phase] || phase;
    }
    screenToBoard(screenX, screenY) {
        const start = this.origin();
        const relX = screenX - start.x;
        const relY = screenY - start.y;
        const x = Math.round(relX / this.cellSize);
        const y = Math.round(relY / this.cellSize);
        const p = this.point({
            x,
            y
        });
        const dist = Math.hypot(screenX - p.x, screenY - p.y);
        if (x < 0 || x >= BOARD_WIDTH || y < 0 || y >= BOARD_HEIGHT || dist > this.cellSize * 0.48) {
            return null;
        }
        return {
            x,
            y
        };
    }
}


// ---- browser app ----
const STORAGE_KEY = 'xili_leaderboard_v1';
const NAME_KEY = 'xili_last_player_name';

const browserStorage = {
  read()  { try { return localStorage.getItem(STORAGE_KEY); } catch (_) { return null; } },
  write(v){ try { localStorage.setItem(STORAGE_KEY, v); } catch (_) { /* private mode */ } },
};

function readLastName() {
  try { return localStorage.getItem(NAME_KEY) || ''; } catch (_) { return ''; }
}
function writeLastName(name) {
  try { localStorage.setItem(NAME_KEY, name); } catch (_) { /* ignore */ }
}

function createDemoState() {
  const state = createInitialState();
  spawnEnemies(state);
  updateThreatMap(state);
  return state;
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, c => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  }[c]));
}

function renderLeaderboardOverlay(state, currentEntry) {
  const overlay = document.getElementById('leaderboard-overlay');
  if (!overlay) return;
  const entries = loadLeaderboard(browserStorage);
  const rank = currentEntry ? getRank(entries, currentEntry) : null;

  let rowsHtml;
  if (entries.length === 0) {
    rowsHtml = '<div class="leaderboard-empty">尚无记录</div>';
  } else {
    const rows = entries.map((e, i) => {
      const isCurrent = currentEntry && e.timestamp === currentEntry.timestamp && e.name === currentEntry.name;
      const cls = isCurrent ? ' class="current"' : '';
      const mark = e.isVictory ? ' 🏆' : '';
      return '<tr' + cls + '>' +
        '<td class="rank">' + (i + 1) + '</td>' +
        '<td>' + escapeHtml(e.name) + mark + '</td>' +
        '<td class="score">' + e.score + '</td>' +
        '<td class="time">' + formatElapsed(e.elapsedSec) + '</td>' +
        '</tr>';
    }).join('');
    rowsHtml = '<table class="leaderboard-table">' +
      '<thead><tr><th>#</th><th>名字</th><th>分数</th><th>时间</th></tr></thead>' +
      '<tbody>' + rows + '</tbody></table>';
  }

  const rankLine = rank
    ? '<div class="rank-line">本局排名：第 ' + rank + ' 名</div>'
    : (currentEntry ? '<div class="rank-line">未上榜（成绩低于第 10 名）</div>' : '');

  const closeLabel = currentEntry ? '再来一局' : '关闭';
  const closeAction = currentEntry ? 'restart' : 'close';

  overlay.innerHTML =
    '<div class="modal">' +
      '<h2>🏆 排行榜 (Top 10)</h2>' +
      rankLine +
      rowsHtml +
      '<div class="actions">' +
        '<button type="button" class="secondary" data-action="clear">清空榜单</button>' +
        '<button type="button" data-action="' + closeAction + '">' + closeLabel + '</button>' +
      '</div>' +
    '</div>';
  overlay.hidden = false;

  const closeBtn = overlay.querySelector('[data-action="restart"], [data-action="close"]');
  closeBtn.addEventListener('click', () => {
    overlay.hidden = true;
    overlay.innerHTML = '';
    if (closeAction === 'restart') {
      window.__xiliRestart && window.__xiliRestart();
    }
  });
  overlay.querySelector('[data-action="clear"]').addEventListener('click', () => {
    if (window.confirm('确定清空全部历史记录？此操作无法撤销。')) {
      clearLeaderboard(browserStorage);
      renderLeaderboardOverlay(state, currentEntry);
    }
  });
}

function renderResultOverlay(state) {
  const overlay = document.getElementById('leaderboard-overlay');
  if (!overlay) return;

  const elapsedSec = Math.floor(getElapsedGameMs(state) / 1000);
  const lastName = readLastName();

  overlay.innerHTML =
    '<div class="modal">' +
      '<h2>' + (state.isVictory ? '胜利！' : '游戏结束') + '</h2>' +
      '<div class="stats">' +
        '<span class="k">得分</span><span class="v">' + state.score + '</span>' +
        '<span class="k">回合</span><span class="v">' + state.turn + '</span>' +
        '<span class="k">时间</span><span class="v">' + formatElapsed(elapsedSec) + '</span>' +
      '</div>' +
      '<label for="player-name">你的名字</label>' +
      '<input id="player-name" type="text" maxlength="' + MAX_NAME_LENGTH + '" placeholder="匿名" value="' + escapeHtml(lastName) + '">' +
      '<div class="actions">' +
        '<button type="button" class="secondary" data-action="skip">不保存</button>' +
        '<button type="button" data-action="save">保存成绩</button>' +
      '</div>' +
    '</div>';
  overlay.hidden = false;

  const input = overlay.querySelector('#player-name');
  input.focus();
  input.select();

  function save() {
    const rawName = input.value;
    const name = normalizeName(rawName);
    writeLastName(name);
    const entry = {
      name,
      score: state.score,
      turn: state.turn,
      elapsedSec,
      isVictory: !!state.isVictory,
      timestamp: Date.now(),
    };
    insertEntry(browserStorage, entry);
    renderLeaderboardOverlay(state, entry);
  }
  function skip() {
    const entry = {
      name: normalizeName(input.value),
      score: state.score,
      turn: state.turn,
      elapsedSec,
      isVictory: !!state.isVictory,
      timestamp: Date.now(),
    };
    // 不写入 storage，但传入 currentEntry 仅用于在榜外提示「未上榜」
    renderLeaderboardOverlay(state, entry);
  }

  overlay.querySelector('[data-action="save"]').addEventListener('click', save);
  overlay.querySelector('[data-action="skip"]').addEventListener('click', skip);
  input.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') { e.preventDefault(); save(); }
  });
}

function renderShopOverlay(state, onClose) {
  const overlay = document.getElementById('leaderboard-overlay');
  if (!overlay) return;
  const cards = state.shopOffers.map(offer => {
    const spec = SKILL_SPECS[offer.skillId];
    const status = canPurchaseOffer(state, offer);
    const disabled = status !== 'purchased';
    const label = offer.purchased ? '售罄'
      : status === 'max_level' ? '已满级'
      : status === 'insufficient_coins' ? '金币不足'
      : offer.price + ' 金币购买';
    return '<article class="shop-card" data-offer-id="' + offer.id + '">' +
      '<h3>' + escapeHtml(spec.icon + ' ' + spec.name) + ' Lv.' + state.skills[offer.skillId] + '</h3>' +
      '<p>' + escapeHtml(spec.desc) + '</p>' +
      '<button type="button" data-action="buy" data-offer-id="' + offer.id + '"' +
        (disabled ? ' disabled' : '') + '>' + label + '</button>' +
      '</article>';
  }).join('');

  overlay.innerHTML =
    '<div class="modal shop-modal">' +
      '<h2>技能商店</h2>' +
      '<div class="rank-line">金币：<span data-shop-coins>' + state.coins + '</span></div>' +
      '<div class="shop-cards">' + cards + '</div>' +
      '<div class="actions"><button type="button" data-action="continue">继续战斗</button></div>' +
    '</div>';
  overlay.hidden = false;
  overlay.querySelectorAll('[data-action="buy"]').forEach(button => {
    button.addEventListener('click', () => {
      purchaseShopOffer(state, button.getAttribute('data-offer-id'));
      renderShopOverlay(state, onClose);
    });
  });
  overlay.querySelector('[data-action="continue"]').addEventListener('click', onClose);
}

function startWebDemo() {
  const canvas = document.getElementById('game-canvas');
  const status = document.getElementById('status');
  const restartButton = document.getElementById('restart-button');
  const overlay = document.getElementById('leaderboard-overlay');
  if (!canvas) throw new Error('Missing #game-canvas');

  const dpr = Math.max(1, window.devicePixelRatio || 1);
  const cssWidth = 960;
  const cssHeight = 760;
  canvas.width = Math.floor(cssWidth * dpr);
  canvas.height = Math.floor(cssHeight * dpr);
  canvas.style.width = cssWidth + 'px';
  canvas.style.height = cssHeight + 'px';

  const ctx = canvas.getContext('2d');
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  const renderCanvas = document.createElement('canvas');
  renderCanvas.width = cssWidth;
  renderCanvas.height = cssHeight;
  const renderer = new CanvasRenderer(renderCanvas);
  let state = createDemoState();
  let lastShownPhase = null;
  let tickHandle = null;

  function draw() {
    renderer.render(state);
    ctx.clearRect(0, 0, cssWidth, cssHeight);
    ctx.drawImage(renderCanvas, 0, 0);
    if (status) {
      status.textContent = state.phase === GamePhase.GAME_OVER
        ? (state.deathMessage || '游戏结束')
        : '点击绿色交点移动，红色区域为敌方威胁。';
    }
    // 进入 GAME_OVER 时打开结算面板（只触发一次）
    if (state.phase === GamePhase.SHOP && lastShownPhase !== GamePhase.SHOP) {
      renderShopOverlay(state, continueAfterShop);
    }
    if (state.phase === GamePhase.GAME_OVER && lastShownPhase !== GamePhase.GAME_OVER) {
      stopTick();
      renderResultOverlay(state);
    }
    lastShownPhase = state.phase;
  }

  function startTick() {
    if (tickHandle) return;
    tickHandle = window.setInterval(() => {
      if (state.phase !== GamePhase.GAME_OVER) draw();
    }, 1000);
  }
  function stopTick() {
    if (tickHandle) { window.clearInterval(tickHandle); tickHandle = null; }
  }

  function restart() {
    if (overlay) { overlay.hidden = true; overlay.innerHTML = ''; }
    state = createDemoState();
    lastShownPhase = null;
    startTick();
    draw();
  }
  window.__xiliRestart = restart;

  function continueAfterShop() {
    closeShop(state);
    if (overlay) { overlay.hidden = true; overlay.innerHTML = ''; }
    lastShownPhase = null;
    draw();
  }

  canvas.addEventListener('click', (event) => {
    if (overlay && !overlay.hidden) return; // 弹窗时禁用棋盘点击
    if (state.phase === GamePhase.GAME_OVER) return;
    if (state.phase !== GamePhase.PLAYER_TURN || state.animating) return;

    const rect = canvas.getBoundingClientRect();
    const target = renderer.screenToBoard(event.clientX - rect.left, event.clientY - rect.top);
    if (!target) return;

    const result = handlePlayerMove(state, target);
    if (!result.moved) return;
    draw();

    window.setTimeout(() => {
      if (state.phase === GamePhase.ENEMY_TURN) {
        executeEnemyTurn(state);
        draw();
      }
    }, 180);
  });

  if (restartButton) restartButton.addEventListener('click', restart);
  const leaderboardButton = document.getElementById('leaderboard-button');
  if (leaderboardButton) leaderboardButton.addEventListener('click', () => {
    renderLeaderboardOverlay(state, null);
  });
  startTick();
  draw();
  window.ProjectXiliDemo = {
    getState: () => state,
    restart,
    // —— 测试钩子；生产环境无害，仅供 Playwright E2E 使用 ——
    __test: {
      forceGameOver(opts) {
        opts = opts || {};
        state.score = opts.score == null ? 0 : opts.score;
        state.turn = opts.turn == null ? 1 : opts.turn;
        state.startedAt = Date.now() - (opts.elapsedSec || 0) * 1000;
        state.finishedAt = Date.now();
        state.isVictory = !!opts.isVictory;
        state.deathMessage = opts.message || '测试触发';
        state.phase = GamePhase.GAME_OVER;
        draw();
      },
      clearStorage() {
        try {
          localStorage.removeItem(STORAGE_KEY);
          localStorage.removeItem(NAME_KEY);
        } catch (_) { /* ignore */ }
      },
      seedLeaderboard(entries) {
        try {
          localStorage.setItem(STORAGE_KEY, JSON.stringify(entries));
        } catch (_) { /* ignore */ }
      },
      seedLeaderboardRaw(rawString) {
        try {
          localStorage.setItem(STORAGE_KEY, rawString);
        } catch (_) { /* ignore */ }
      },
      readLeaderboard() {
        try { return localStorage.getItem(STORAGE_KEY); } catch (_) { return null; }
      },
      seedLastName(name) {
        try { localStorage.setItem(NAME_KEY, name); } catch (_) { /* ignore */ }
      },
      grantSkill(id) {
        // Explicit test-only grant path; production skill growth goes through shop purchases.
        if (!grantSkill(state, id)) throw new Error('cannot grant skill: ' + id);
        draw();
      },
      setSkillLevel(id, level) {
        if (state.skills[id] == null) throw new Error('unknown skill: ' + id);
        state.skills[id] = level;
        draw();
      },
      // 暴露纯函数给端到端测试断言（非 UI 路径）
      getScalingValue: getScalingValue,
      SKILL_SPECS: SKILL_SPECS,
      awardScore(amount) { awardScore(state, amount); draw(); },
      openShop(now) { const opened = maybeOpenShop(state, now); draw(); return opened; },
      purchaseOffer(id) { const result = purchaseShopOffer(state, id); draw(); return result; },
      closeShop() { continueAfterShop(); },
      setShopOffers(skillIds) {
        state.shopOffers = skillIds.map((skillId, i) => ({ id: 'test_' + i, skillId, price: SHOP_PRICE, purchased: false }));
        state.phase = GamePhase.SHOP;
        state.shopOpenedAt = Date.now();
        draw();
      },
      getElapsedGameMs: () => getElapsedGameMs(state),
      executeEnemyTurn: () => executeEnemyTurn(state),
    },
  };
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', startWebDemo);
} else {
  startWebDemo();
}

})();
